/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package db;
import java.sql.*;
import java.util.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        Class.forName("org.postgresql.Driver");
        System.out.println("Driver loaded");
        Scanner sc=new Scanner(System.in);
        Connection con;
        String uname;
        String pass;
        System.out.println("ENter Username");
        uname=sc.next();
        System.out.println("Enter password");
        pass=sc.next();
        con= DriverManager.getConnection("jdbc:postgresql://localhost:5432/test", uname, pass);
        System.out.println("Connection done");


        System.out.println(" 1.Insert value\n 2.Update table\n 3.create table\n 4.Delete value");

        System.out.println("Enter choice");
        int choice;
        choice=sc.nextInt();
        Statement stmt;
        stmt=con.createStatement();
        switch(choice){
            case 1:
            System.out.println("Enter the Id : ");
            int id = sc.nextInt();
            System.out.println("Enter the Name : ");
            String name = sc.next();
            String sql;
            sql = "insert into employee values(" + id + ",'" + name + "')";
            stmt.executeUpdate(sql);
            System.out.println("\t\t Successfully Record Inserted ! ");
            break;

            case 2:
            //String sql;
             //String name;
             System.out.println("Enter the Id : ");
            int id = sc.nextInt();
            System.out.println("Enter the Name : ");
            String name = sc.next();
            sql = "update student set name = '" + name + "' where id = '" + id + "'";
            stmt.executeUpdate(sql);
            System.out.println("\t\t successfully record Updated ! ");

           
        }



    }
}
