/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jcp;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Student st=new Student();
        st.setId(5);
        st.setName("test");
        stImpl ob;
        ob=new stImpl();
        //ob.update(st);
        //ob.delete(st);
        ob.select(st);
        ob.insert(st);
    }
}
